### ISSUE TITLE
Breaks the build with ember-bootstrap

### ISSUE THREAD

**Issue by vlascik** [lifeart/ember-cli-fallback-builds#4]
Steps to reproduce:
```
ember new fallback-repro
cd fallback-repro
ember install ember-bootstrap ember-cli-fallback-builds
ember build:fallback --prod
```
Results:
```
cleaning up...
Build failed.
Build failed.
Build Error (Funnel)

ENOENT: no such file or directory, unlink 'C:\Temp\broccoli-24348vrmOD9jfI8eG\out-099-funnel/components/bs3/bs-navbar/toggle.hbs'

    at Object.unlinkSync (fs.js:951:3)
    at Funnel.applyPatch [as _applyPatch] (P:\Projects\fallback-repro\node_modules\broccoli-funnel\index.js:374:10)
    at Funnel.<anonymous> (P:\Projects\fallback-repro\node_modules\broccoli-funnel\index.js:350:10)
    at Array.forEach (<anonymous>)
    at Funnel.processFilters (P:\Projects\fallback-repro\node_modules\broccoli-funnel\index.js:349:11)
    at Funnel.build (P:\Projects\fallback-repro\node_modules\broccoli-funnel\index.js:259:10)
    at resolve (P:\Projects\fallback-repro\node_modules\broccoli\lib\wrappers\transform-node.js:29:35)
    at new Promise (<anonymous>)
    at TransformNodeWrapper.build (P:\Projects\fallback-repro\node_modules\broccoli\lib\wrappers\transform-node.js:21:12)
    at Promise.resolve.then.then.then (P:\Projects\fallback-repro\node_modules\broccoli\lib\builder.js:116:28)
```

regular `ember build --prod` works

**Comment by lifeart** [comment]
fixed in `"ember-cli-fallback-builds": "0.0.6"`
