### ISSUE TITLE
Another build break

### ISSUE THREAD

**Issue by vlascik** [lifeart/ember-cli-fallback-builds#7]
Yesterday's fix worked, simple reproduction app now builds, but my larger app fails with a different error:
```
  ember-cli:command `build:fallback` command running `Build` task +3ms
- Building  broccoli-stew:rename [Funnel] from: .js to: .fb.js +0ms
  broccoli-stew:rename [Funnel] from: .html to: .fb.html +2ms
  ember-cli:command An error occurred running `Build` from the `build:fallback` command. BuilderError: Directory not found: C:\Users\z\AppData\Local\Temp\tmp-47004Hz2HgWt1lk0L\legacy
    at Builder.checkInputPathsExist (P:\Project\node_modules\broccoli\lib\builder.js:268:15)
    at new Builder (P:\Project\node_modules\broccoli\lib\builder.js:66:10)
    at buildsMerger (P:\Project\node_modules\ember-cli-fallback-builds\lib\utils\builds-merger.js:48:19)
    at BuildTask.run (P:\Project\node_modules\ember-cli-fallback-builds\lib\tasks\build.js:85:16)
    at Promise.resolve.then (P:\Project\node_modules\ember-cli\lib\models\command.js:239:24)
    at tryCatcher (P:\Project\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:326:21)
    at invokeCallback (P:\Project\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:498:33)
    at P:\Project\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:562:16
    at flush (P:\Project\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2441:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
 +15s
  ember-cli:project getProjectRoot P:\Project -> P:\Project +3ms
  ember-cli:project getProjectRoot P:\Project -> P:\Project +2ms
Directory not found: C:\Users\z\AppData\Local\Temp\tmp-47004Hz2HgWt1lk0L\legacy
```
Any idea what could cause this, or should I debug it more?

**Comment by lifeart** [comment]
is it  "ember-cli-fallback-builds@0.0.7"?

**Comment by lifeart** [comment]
if we have legacy build error -> we don't have legacy output, this is the root for issue.

**Comment by vlascik** [comment]
> is it "ember-cli-fallback-builds@0.0.7"?

yes

> if we have legacy build error -> we don't have legacy output, this is the root for issue.

yep, seems that `dummyBuilder` doesn't create the output directory, and build itself doesn't create it either. maybe it should make sure the folders exist before spawning the builds

**Comment by lifeart** [comment]
@vlascik try run build under `administrator` rights.

**Comment by vlascik** [comment]
It was running with administrator rights. Seems that this is the same problem as in https://github.com/lifeart/ember-cli-fallback-builds/issues/8

**Comment by lifeart** [comment]
Could you try againist `0.0.8`? (debug output added)

**Comment by vlascik** [comment]
Tried it, same thing, and there is no additional debug output, result is not returned, it fails during the spawned build. Maybe it's a bug in e-cli builder itself if the output directory doesn't exist hm, so, maybe the dummyBuilder should create it before spawning the build first? Not sure if e-cli has any code that does it or just relies on `dist/` already existing.
```
  ember-cli:command An error occurred running `Build` from the `build:fallback` command. BuilderError: Directory not found: C:\Users\z\AppData\Local\Temp\tmp-25856CSIwKM86XhNo\legacy
    at Builder.checkInputPathsExist (P:\Project\node_modules\broccoli\lib\builder.js:268:15)
```
