### ISSUE TITLE
Error regarding missing directory

### ISSUE THREAD

**Issue by meirish** [lifeart/ember-cli-fallback-builds#8]
I was trying this out and got the following error when running `ember build:fallback -prod`:

```  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Directory not found: /var/folders/n0/1cj2fwvj7hggltr7zqn8g9v40000gp/T/tmp-78479hej9tIuSzYm1/legacy
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Directory not found: /var/folders/n0/1cj2fwvj7hggltr7zqn8g9v40000gp/T/tmp-78479hej9tIuSzYm1/legacy
  - name: BuilderError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: BuilderError: Directory not found: /var/folders/n0/1cj2fwvj7hggltr7zqn8g9v40000gp/T/tmp-78479hej9tIuSzYm1/legacy
    at Builder.checkInputPathsExist (/Users/meirish/code/vault/ui/node_modules/broccoli/lib/builder.js:261:15)
    at new Builder (/Users/meirish/code/vault/ui/node_modules/broccoli/lib/builder.js:65:10)
    at buildsMerger (/Users/meirish/code/vault/ui/node_modules/ember-cli-fallback-builds/lib/utils/builds-merger.js:48:19)
    at BuildTask.run (/Users/meirish/code/vault/ui/node_modules/ember-cli-fallback-builds/lib/tasks/build.js:85:16)
    at Promise.resolve.then (/Users/meirish/code/vault/ui/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/meirish/code/vault/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/meirish/code/vault/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/meirish/code/vault/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/meirish/code/vault/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)```

**Comment by lifeart** [comment]
Hi! Thank you for report! Could you try againist `0.0.8`? (debug output added)

**Comment by meirish** [comment]
Same thing, with just an additional undefined element in the error summary
```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Directory not found: /var/folders/n0/1cj2fwvj7hggltr7zqn8g9v40000gp/T/tmp-1162686XEha0Fqi6J/legacy
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Directory not found: /var/folders/n0/1cj2fwvj7hggltr7zqn8g9v40000gp/T/tmp-1162686XEha0Fqi6J/legacy
  - name: BuilderError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: BuilderError: Directory not found: /var/folders/n0/1cj2fwvj7hggltr7zqn8g9v40000gp/T/tmp-1162686XEha0Fqi6J/legacy
    at Builder.checkInputPathsExist (/Users/meirish/code/vault/ui/node_modules/broccoli/lib/builder.js:261:15)
    at new Builder (/Users/meirish/code/vault/ui/node_modules/broccoli/lib/builder.js:65:10)
    at buildsMerger (/Users/meirish/code/vault/ui/node_modules/ember-cli-fallback-builds/lib/utils/builds-merger.js:48:19)
    at BuildTask.run (/Users/meirish/code/vault/ui/node_modules/ember-cli-fallback-builds/lib/tasks/build.js:94:16)
    at Promise.resolve.then (/Users/meirish/code/vault/ui/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatcher (/Users/meirish/code/vault/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/meirish/code/vault/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at /Users/meirish/code/vault/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:559:14
    at flush (/Users/meirish/code/vault/ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
